### ISSUE TITLE
Read motor encoders and create functions

### ISSUE THREAD

**Issue by abarnes6** [SIU-Robotics/moondawg-ino#40]

**Comment by abarnes6** [comment]
Encoder is working. Still need function for "positional encoder".

**Comment by BigBroccoli** [comment]
We need to use ESP32Encoder.h and it is very similar but it's also different @Marco-Caliendo

**Comment by BigBroccoli** [comment]
I'm gonna work on getting it to build tonight. on the esp32, there will be a lot of changes. Going to use externs for now till it's a project that works then I'll work on removing them

**Comment by BigBroccoli** [comment]
Here is the [Github for ESP32Encoders](https://github.com/madhephaestus/ESP32Encoder)
