### ISSUE TITLE
Prep code for Arduino alternative

### ISSUE THREAD

**Issue by BigBroccoli** [SIU-Robotics/moondawg-ino#43]
Look into how PlatformIO works and what we will need to do to get it working in our use case.

**Comment by BigBroccoli** [comment]
Look into ESP32's, ATmega based stuff, etc.
[](https://www.espressif.com/en/products/devkits)
[](https://electronics.stackexchange.com/a/435915)
[](https://platformio.org/)

**Comment by BigBroccoli** [comment]
[Guide to Install](https://docs.platformio.org/en/latest/integration/ide/vscode.html#ide-vscode)

**Comment by BigBroccoli** [comment]
This tool will be needed to do dev. It has a lot of useful features
![Image](https://github.com/user-attachments/assets/ef2559af-9d94-4688-9ea7-bea82a18ff53)
![Image](https://github.com/user-attachments/assets/c43e748a-156f-4906-be8b-44a1ebd1fc92)

**Comment by BigBroccoli** [comment]
Also need to add platformIO files to repos. Will add once current PR #45 gets merged to main

**Comment by BigBroccoli** [comment]
Look at comments from Andrews review of #45 to update comments, Readme, some code, etc.

**Comment by Marco-Caliendo** [comment]
Test removing arduino.h from files

**Comment by Marco-Caliendo** [comment]
remove externs, put them in main file or something like that

**Comment by abarnes6** [comment]
esp wrover kit

**Comment by abarnes6** [comment]
[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino

**Comment by BigBroccoli** [comment]
Look for better solution to Structs kinda confusing

**Comment by BigBroccoli** [comment]
Update Readme based on new changes and on Andrew's comments

**Comment by BigBroccoli** [comment]
Make the comments uniform and updated on all code
